apiVersion: v1
kind: ConfigMap
metadata:
    name: shared-vars
    namespace: teastore
data:
    USE_POD_IP: "true"
    REGISTRY_HOST: "teastore-registry"
    DB_HOST: "teastore-db"
    DB_PORT: "3306"
    CATALINA_OPTS: "-XX:+UseG1GC -Xmx512m -Xms512m -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=20"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-db
    namespace: teastore
    labels:
        app: teastore
        run: teastore-db
spec:
    selector:
        matchLabels:
            app: teastore
            run: teastore-db
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-db
        spec:
            containers:
                - name: teastore-db
                  image: descartesresearch/teastore-db
                  ports:
                      - containerPort: 3306
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
    name: teastore-db
    namespace: teastore
    labels:
        app: teastore
        run: teastore-db
spec:
    ports:
        - port: 3306
          protocol: TCP
    selector:
        run: teastore-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-registry
    namespace: teastore
    labels:
        app: teastore
        run: teastore-registry
spec:
    selector:
        matchLabels:
            app: teastore
            run: teastore-registry
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-registry
        spec:
            containers:
                - name: teastore-registry
                  image: descartesresearch/teastore-registry
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
    name: teastore-registry
    namespace: teastore
    labels:
        app: teastore
        run: teastore-registry
spec:
    ports:
        - port: 8080
          protocol: TCP
    selector:
        run: teastore-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-persistence
    namespace: teastore
    labels:
        app: teastore
        run: teastore-persistence
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teastore
            run: teastore-persistence
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-persistence
        spec:
            containers:
                - name: teastore-persistence
                  image: descartesresearch/teastore-persistence
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-auth
    namespace: teastore
    labels:
        app: teastore
        run: teastore-auth
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teastore
            run: teastore-auth
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-auth
        spec:
            containers:
                - name: teastore-auth
                  image: descartesresearch/teastore-auth
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-image
    namespace: teastore
    labels:
        app: teastore
        run: teastore-image
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teastore
            run: teastore-image
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-image
        spec:
            containers:
                - name: teastore-image
                  image: descartesresearch/teastore-image
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-recommender
    namespace: teastore
    labels:
        app: teastore
        run: teastore-recommender
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teastore
            run: teastore-recommender
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-recommender
        spec:
            containers:
                - name: teastore-recommender
                  image: descartesresearch/teastore-recommender
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: teastore-webui
    namespace: teastore
    labels:
        app: teastore
        run: teastore-webui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teastore
            run: teastore-webui
    template:
        metadata:
            labels:
                app: teastore
                run: teastore-webui
        spec:
            containers:
                - name: teastore-webui
                  image: descartesresearch/teastore-webui
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shared-vars
                  resources:
                      limits:
                          cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
    name: teastore-webui
    namespace: teastore
    labels:
        app: teastore
        run: teastore-webui
spec:
    type: NodePort
    ports:
        - port: 8080
          nodePort: 30080
          protocol: TCP
    selector:
        run: teastore-webui
